config/routes.rb
Rails.application.routes.draw do
  root "sessions#new"
  #Rooms
  get "/rooms" => "rooms#index"
  get "/rooms/:id" => "rooms#show"

  # login routes
  get "/signup" => "users#new"
  post "/users" => "users#create"

  # sessions routes
  get "/login" => "sessions#new"
  post "/sessions" => "sessions#create"
  get "/logout" => "sessions#destroy"

  #reservations routes

  get "/reservations" => "reservations#new"
  post "/reservations" => "reservations#create"

  # reviews routes
  resources :reviews
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :room
  has_many :reviews
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :reservation
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :roomimages
  has_many :reservations
  has_many :users, through: :reservations
end

app/models/room_image.rb
class RoomImage < ApplicationRecord
  belongs_to :room
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, presence: true, uniqueness: true
  has_many :reservations
  has_many :rooms, through: :reservations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def authenticate_user
    redirect_to "/login", status: :see_other unless current_user
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  # def index
  #   @reservations = current_user.reservations.where(user_id: current_user.id)
  #   render :index
  # end

  # def show
  #   @reservation = Reservation.find(params[:id])
  # end

  def new
    @reservation = Reservation.new
  end

  # def total_cost
  #   return total
  # end

  def create
    @reservation = Reservation.new(
      user_id: current_user.id,
      room_id: params[:room_id],
      start_date: params[:start_date],
      end_date: params[:end_date],
      price: params[:price],
      total: 1000,
    )

    if @reservation.save
      render json: { message: "it works" }
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def reservation_params
    params.require(:reservation).permit(:start_date, :end_date)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @reviews = Review.all
    render :index
  end

  def new
    @review = Review.new
    render template: "reviews/new"
  end

  def create
    @review = Review.new(
      reservation_id: params[:reservation_id],
      rating: params[:rating],
      comment: params[:comment],
    )
    if @review.save
      redirect_to "/rooms"
    else
      render :new, status: :unprocessable_entity
    end
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Room.all
    render :index
  end

  def show
    @room = Room.find(params[:id])
    render :show
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render template: "sessions/new"
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to "/rooms"
    else
      redirect_to "/login"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to "/login"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render template: "users/new"
  end

  def create
    @user = User.new(
      name: params[:user][:name],
      email: params[:user][:email],
      password: params[:user][:password],
      password_confirmation: params[:user][:password_confirmation],
    )
    if @user.save
      session[:user_id] = @user.id
      redirect_to "/"
    else
      render :new, status: :unprocessable_entity
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirBnbApp</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reservations/_form.html.erb
<% form_with model: reservation do |form| %>
  <div>
    <p>Your Name: <%= current_user.name %></p>
    <p>Property Location: Room City, Room State</p>
    <p><%= form.label :start_date, "Check-in Date:" %>
    <%= form.date_field :start_date %></p>
    <p><%= form.label :end_date, "Check-out Date:" %>
    <%= form.date_field :end_date %></p>
    <p> Price per night: VAR (Rooms Table) </p>
    <p><strong>Total Cost:</strong> CALCULATE (Price * # Nights)</p>
  </div>
  <div>
    <%= form.submit "Complete Reservation" %>
  </div>

  <!-- After confirmation, show a link to leave a review -->
<% end%>

app/views/reservations/new.html.erb
<h1>Reserve this room</h1>

<%= form_with method: "post", url: "/reservations" do |form| %>
  <div>
    <p><%= form.label :start_date, "Check-in Date:" %>
    <%= form.date_field :start_date, :value => Time.now.strftime("%Y-%m-%d") %></p>
    <p><%= form.label :end_date, "Check-out Date:" %>
    <%= form.date_field :end_date, :value => Date.tomorrow.strftime("%Y-%m-%d") %></p>
    <p> <%= form.hidden_field :room_id, :value => params[:room_id], :readonly => true %>
    </p>
    <p><%= form.label :price, "Price per night:" %>
    <%="$" + params[:price]%>
    <%= form.hidden_field :price, :value => params[:price]%>
    </p>
    <p><%= form.label :nights, "Nights:" %>
    <%= "Check-out minus Check-in" %>
    </p>
    <p><%= form.label :total, "Total cost:" %>
    <%="$" + params[:price] + " * Nights" %>
    <%= form.hidden_field :total, :value => 0 %>
    </p>
  </div>
  <div>
    <%= form.submit "Complete Reservation" %>
  </div>

<% end%> 

<!-- 
  # Calculate total
  # Where to go after clicking submit
  # Link to leave review
  >

app/views/reviews/index.html.erb
<%= link_to "New Review", new_review_path %>

app/views/reviews/new.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  </head>
  <body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>


<div class="mx-auto" style="width: 200px;">
<div class="mt-auto" style="height: 100px;">
</div>
<h2>How was
<small class="text-muted">your stay?</small>
</h2>

<%= form_with method: "post", url: "/reviews" do |form| %>

  <div>
    <%=form.label :reservation_id%> <br>
    <%= form.text_field :reservation_id%>
  </div>
  <div>
    <%= form.label :rating %><br>
    <%= form.text_field :rating %>
  </div>

  <div>
    <%= form.label :comment %><br>
    <%= form.text_area :comment %>
  </div>

  <div>
    <%= form.submit "Submit Review (it better be good)", class: "btn btn-outline-secondary" %>

  </div>
  </div>
  </div>
<% end %>

app/views/rooms/index.html.erb
<h1>All Rooms</h1>
<!--If time allows add user filter for city, state, price-->


<% @rooms.each do |room|%>

  <!--Basic Description of Room-->
  <a href="/rooms/<%=room.id%>">
    <div class="container" style="background-color: lightgrey; border-radius: 10px">
    <img src="<%=RoomImage.find(room.id).url%>" width=100% height=auto>
      <div class="row">
        <div class="col">
          <p><%=room.city%>, <%=room.state%><p>
        </div>
        <div class="col">
          <p>Price: $<%=room.price%> per night<p>
        </div>
      </div>
    </div>
  </a>

  <div class="container">
    <div class="row">
      <div class="col-8">
        <p><%=room.description%><p>
      </div>
    </div>
  </div>
<%end%>

<div>
 <%= link_to "Logout", logout_path%>
 </div>

app/views/rooms/show.html.erb
<h1>Room Details</h1>

<!---Image of Room-->


<!--Basic Description of Rom-->
<div class="container" style="background-color: lightgrey; border-radius: 10px">
  <img src="<%=RoomImage.find(@room.id).url%>" width=100% height=auto style="border-radius: 10px">
  <div class="row">
    <div class="col">
      <p><%=@room.city%>, <%=@room.state%><p>
    </div>
    <div class="col">
      <p>Price: $<%=@room.price%> per night<p>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-8">
          <p><%=@room.description%><p>
        </div>
        <div class ="col-4">
          <!--Display link conditional if user is login in or not-->
          <%if current_user%>
            <p><%= link_to "Make a reservation", reservations_path(room_id: @room.id, price: @room.price) %></p>
          <%else%>
            <p><a href="/login">Login or Sign Up to Reserve</a></P>
          <%end%>
        </div>
      </div>
    </div>
  </div>
  
  </div>
</div>

<!--Room Details-->
<div class="row">
  <div class="col-sm-9">
    <p>Home Type: <%=@room.home_type%> Room Type: <%=@room.room_type%> <p>
    <div class="row">
      <div class="col-8 col-sm-6">
        <p>Occupancy: <%=@room.total_occupancy%><p>
        <p>Bedrooms: <%=@room.total_bedrooms%><p>
      </div>
      <div class="col-4 col-sm-6">
        <p>Bathrooms: <%=@room.total_bathrooms%><p>
      </div>
    </div>
  </div>
</div>


<!--Click to go back to (index action)-->
<p><a href="/rooms/">Back to All Rooms</a></p>


<h1>Reviews</h1>
<p><a href="/reviews/new">Leave a Review</a></p>

<%Reservation.all.each do |reservation|%>
  <%if reservation.room_id == @room.id%>
    <p>Comment: <%=reservation.reviews.first.comment%></p>
    <p>Rating: <%=reservation.reviews.first.rating%></p>
  <%end%>
<%end%>

app/views/users/new.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  </head>
  <body>
      <div class="card text-center" style="width: 100%; height: 50%;">
      <img src="https://d3.harvard.edu/platform-digit/wp-content/uploads/sites/2/2020/04/unnamed-1-512x200.png" class="card-img-top" alt="...">
      
        <div class="card-header">
         <h2><b>Sign Up</b></h2>
        </div>

            <h4><b> Please enter your infromation below and click the button "Create Account" when you are finished</b></h4>

            <%= form_with model: @user do |form| %>   

            <div>
              <%= form.label :name %>
              <%= form.text_field :name %>
              <% @user.errors.full_messages_for(:name).each do |message| %>
                <div><%= message %></div>
              <% end %>
            </div>
            <div>
              <%= form.label :email %>
              <%= form.email_field :email %>
              <% @user.errors.full_messages_for(:email).each do |message| %>
                <div><%= message %></div>
              <% end %>
            </div>
            <div>
              <%= form.label :password %>
              <%= form.password_field :password %>
              <% @user.errors.full_messages_for(:password).each do |message| %>
                <div><%= message %></div>
              <% end %>
            </div>
            <div>
              <%= form.label :password_confirmation %>
              <%= form.password_field :password_confirmation %>
              <% @user.errors.full_messages_for(:password_confirmation).each do |message| %>
                <div><%= message %></div>
              <% end %>
            </div>
            <div>
              <%= form.submit "Create Account", class: "btn btn-danger btn-lg" %>
            </div>
          </div>
        </div>    
      <% end %>

      <p style="text-center"><center><b> If you already have an account, click the link below to sign up </b></center></p>
      <div class="text-center">
      <%= link_to "Login  ", login_path, class: "btn btn-warning btn-lg" %>
      </div>

      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>